# Standard environment for developing MDSAPT.

name: mdsapt
channels:
  - psi4
  - conda-forge
  - defaults
dependencies:
  # This must be specified FIRST to avoid packaging errors.
  - psi4>=1.6.1,<1.7

  - mdanalysis>=2.2.0,<2.3
  - click
  - numpy
  - openmm
  - pandas
  - pdbfixer
  - pytest
  - pydantic
  - pytest-cov
  - pyyaml
  - rdkit

  # Optional deps
  - nglview

  # Development deps
  - autopep8
  - pylint
  - pyright # type-checking
  - pytest
  - pytest-cov
  - sphinx
  - sphinx_rtd_theme
