# Standard environment for developing MDSAPT.

name: mdsapt
channels:
  - psi4
  - conda-forge
  - defaults
dependencies:
  - mdanalysis
  - nglview
  - numpy
  - openmm
  - pandas
  - pdbfixer
  - psi4
  - pytest
  - pytest-cov
  - pyyaml
  - rdkit
