# Standard environment for developing MDSAPT.

name: mdsapt
channels:
  - psi4
  - conda-forge
  - defaults
dependencies:
  - click
  - mdanalysis>=2.0.0, <2.1
  - nglview>=3.0.3, <3.1
  - numpy
  - openmm
  - pandas
  - pdbfixer
  - psi4
  - pytest-cov
  - pyyaml
  - rdkit
