# Standard environment for developing MDSAPT.

name: mdsapt
channels:
  - conda-forge
  - defaults
dependencies:
  # This must be specified FIRST to avoid packaging errors.
  - python >=3.8
  - psi4 =>1.9.1
  - mdanalysis >=2.7.0
  - rdkit >=2023.09.5
  - openmm >=8.1.1
  - pdbfixer >=1.9
  - numpy
  - click
  - pandas
  - pyarrow # needed for pandas
  - pyyaml

  # Optional deps
  - nglview

  # Development deps
  - autopep8
  - pylint
  - pyright # type-checking
  - pytest
  - pytest-cov
  - sphinx
  - sphinx_rtd_theme
