name: mdsapt
channels:
  - omnia
  - psi4
  - conda-forge
  - defaults
dependencies:
  - mdanalysis>=2.0.0, <2.1
  - nglview>=3.0.3, <3.1
  - numpy>=1, <2
  - openmm=7.5.1
  - pandas
  - pdbfixer=1.6
  - psi4=1.4+9485035
  - pytest-cov
  - pyyaml
  - rdkit>=2020.09.3