# Standard environment for developing MDSAPT.

name: mdsapt
channels:
  - psi4
  - conda-forge
  - defaults
dependencies:
  - mdanalysis
  - numpy
  - openmm
  - pandas
  - pdbfixer
  - psi4
  - pytest
  - pydantic
  - pytest-cov
  - pyyaml
  - rdkit

  # Optional deps
  - nglview

  # Development deps
  - autopep8
  - pylint
  - pyright # type-checking
  - pytest
  - pytest-cov
  - sphinx
  - sphinx_rtd_theme