name: docs
channels:
  - omnia
  - psi4
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - sphinx
  - sphinx_rtd_theme
  - mdanalysis>=2.0.0, <2.1
  - psi4=1.4
  - rdkit>=2020.09.3
  - openmm=7.5.1
  - pdbfixer=1.6
  - pandas
  - numpy>=1, <2
  - nglview>=3.0.3, <3.1
  - pyyaml

  # Pip-only installs
  - pip:

