name: CI

on:
  # Run CI on all pushed commits.
  push: {}

  # Run CI nightly at 03:00 PST (11:00 UTC).
  schedule:
    - cron: "0 11 * * *"

jobs:
  # TODO: set up documentation tests/deployment
  test:
    name: Test MDSAPT on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    # Cache our conda packages.
    # More info: https://github.com/conda-incubator/setup-miniconda#caching-packages
    - name: Cache conda environment
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-py${{ matrix.python-version }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

    # More info on options: https://github.com/conda-incubator/setup-miniconda
    - name: Set up Anaconda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml
        channels: conda-forge,omnia,psi4,defaults
        activate-environment: mdsapt
        auto-update-conda: false
        auto-activate-base: false
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

    - name: Install MDSAPT package
      # conda setup requires this special shell
      shell: bash -l {0}
      run: |
        python -m pip install . --no-deps
        conda list

    - name: Run tests
      # conda setup requires this special shell
      shell: bash -l {0}
      run: |
        pip install pytest-cov
        pytest -v ./mdsapt --cov=mdsapt --cov-report=xml

    - name: Upload CodeCov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}

  # TODO: set up deployment job
